# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Configuración de memoria optimizada para procesadores de 2 núcleos / 4 hilos (i3)
# Se asignan 2GB de Heap y 768MB de Metaspace sin saturar la RAM física del sistema
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

# Limita el número de subprocesos concurrentes de compilación
# Evita picos de CPU del 100% que puedan reiniciar tu laptop
org.gradle.workers.max=2

# Desactiva la ejecución en paralelo para proteger la temperatura y estabilidad del procesador
org.gradle.parallel=false

# Mantiene el Daemon activo en segundo plano para agilizar compilaciones subsecuentes sin reasignar memoria
org.gradle.daemon=true

# Optimización de caché de configuración para acelerar la sincronización
org.gradle.configuration-cache=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

#Para solucionar los problemas de compilacion de BUILT-in Kotlin
android.builtInKotlin=false
android.newDsl=false